# Generated by Django 5.0 on 2024-04-08 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='sub_email',
            new_name='email',
        ),
    ]
