# Generated by Django 5.0 on 2024-04-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_rename_sub_email_subscribe_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
