# Generated by Django 5.0 on 2024-04-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_img', models.ImageField(default=None, max_length=250, null=True, upload_to='blog/')),
                ('blog_author', models.CharField(max_length=100)),
                ('blog_date', models.DateField()),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_dec', models.CharField(max_length=500)),
            ],
        ),
    ]
