# Generated by Django 5.0 on 2024-04-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_img', models.ImageField(default=None, max_length=250, null=True, upload_to='categorie/')),
                ('categorie_name', models.CharField(max_length=50)),
                ('categorie_discount', models.CharField(max_length=100)),
            ],
        ),
    ]
