# Generated by Django 5.0 on 2024-04-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_img', models.ImageField(default=None, max_length=250, null=True, upload_to='reviewer/')),
                ('reviewer_name', models.CharField(max_length=50)),
                ('reviewer_dec', models.CharField(max_length=100)),
            ],
        ),
    ]
