# Generated by Django 5.0 on 2024-04-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='reviewer_dec',
            field=models.CharField(max_length=500),
        ),
    ]
