# Generated by Django 5.0 on 2024-04-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_img', models.ImageField(default=None, max_length=250, null=True, upload_to='feature/%y')),
                ('feature_name', models.CharField(max_length=50)),
                ('feature_dec', models.CharField(max_length=100)),
            ],
        ),
    ]
