# Generated by Django 5.0 on 2024-04-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='feature_img',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='feature/'),
        ),
    ]
