# Generated by Django 5.0 on 2024-04-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.ImageField(default=None, max_length=250, null=True, upload_to='product/')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=20)),
            ],
        ),
    ]
